name: Create Modpack Release and Handle Updater Files

on:
    push:
        branches:
            - main
        paths:
            - "CHANGELOG.md"

jobs:
    create-release:
        runs-on: ubuntu-latest

        steps:
            # 1. Checkout repository with full history to access tags
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Fetch all history to include tags

            # 2. Check if CHANGELOG.md was modified and extract latest version
            - name: Check CHANGELOG.md modification and set up environment
              id: setup
              run: |
                  if git diff --name-only HEAD^ HEAD | grep -q "CHANGELOG.md"; then
                    LATEST_VERSION=$(sed -n '/^##\s*v[0-9]/p' CHANGELOG.md | head -n1 | sed 's/^## v//')
                    echo "changelog_modified=true" >> $GITHUB_OUTPUT
                    echo "VERSION=$LATEST_VERSION" >> $GITHUB_OUTPUT
                    echo "ZIP_NAME=Mel-$LATEST_VERSION.zip" >> $GITHUB_OUTPUT
                  else
                    echo "changelog_modified=false" >> $GITHUB_OUTPUT
                  fi

            # 3. Set environment variables if CHANGELOG.md was modified
            - name: Set environment variables
              if: steps.setup.outputs.changelog_modified == 'true'
              run: |
                  echo "VERSION=${{ steps.setup.outputs.VERSION }}" >> $GITHUB_ENV
                  echo "ZIP_NAME=${{ steps.setup.outputs.ZIP_NAME }}" >> $GITHUB_ENV

            # 4. Find changed files excluding CHANGELOG.md
            - name: Find changed files
              if: steps.setup.outputs.changelog_modified == 'true'
              id: changed_files
              run: |
                  # 获取所有更改的文件，并排除 CHANGELOG.md
                  CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep -v "^CHANGELOG.md$")

                  # 检查是否有其他文件被更改
                  if [ -z "$CHANGED_FILES" ]; then
                    echo "No changed files to process."
                    echo "changed_files=" >> $GITHUB_OUTPUT
                  else
                    echo "changed_files<<EOF" >> $GITHUB_OUTPUT
                    echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
                    echo "EOF" >> $GITHUB_OUTPUT
                  fi

            # 5. Copy changed files to temporary updater/hotfixes directory
            - name: Copy changed files to updater/hotfixes
              if: steps.setup.outputs.changelog_modified == 'true' && steps.changed_files.outputs.changed_files != ''
              run: |
                  mkdir -p updater/hotfixes/${{ env.VERSION }}
                  while IFS= read -r file; do
                    mkdir -p "updater/hotfixes/${{ env.VERSION }}/$(dirname "$file")"
                    cp "$file" "updater/hotfixes/${{ env.VERSION }}/$file"
                  done <<< "${{ steps.changed_files.outputs.changed_files }}"

            # 6. Generate hashes and save to updater/hashes/{VERSION}/hashes.txt
            - name: Generate hashes for changed files
              if: steps.setup.outputs.changelog_modified == 'true' && steps.changed_files.outputs.changed_files != ''
              run: |
                  mkdir -p updater/hashes/${{ env.VERSION }}
                  find updater/hotfixes/${{ env.VERSION }} -type f | while read -r filepath; do
                    # Remove 'updater/hotfixes/{VERSION}/' from filepath
                    relative_path=${filepath#updater/hotfixes/${{ env.VERSION }}/}
                    # Compute sha256 hash
                    hash=$(sha256sum "$filepath" | awk '{print $1}')
                    # Output in 'path|hash' format
                    echo "${relative_path}|${hash}"
                  done > updater/hashes/${{ env.VERSION }}/hashes.txt

            # 7. Extract current version's CHANGELOG and save to updater/versions/{VERSION}/changelog.txt
            - name: Extract CHANGELOG for current version
              if: steps.setup.outputs.changelog_modified == 'true'
              run: |
                  mkdir -p updater/versions/${{ env.VERSION }}
                  sed -n "/^## v${{ env.VERSION }}/,/^## /p" CHANGELOG.md | sed '$d' > updater/versions/${{ env.VERSION }}/changelog.txt

            # 8. Create and package modpack (overrides and required files only)
            - name: Create and package modpack
              if: steps.setup.outputs.changelog_modified == 'true'
              run: |
                  mkdir -p overrides
                  # 复制指定的目录到 overrides
                  cp -r config defaultconfigs hotai kubejs ldlib overrides/ || echo "Some directories might not exist."
                  # 包含 hashes.txt 到 overrides 中
                  cp updater/hashes/${{ env.VERSION }}/hashes.txt overrides/hashes.txt || echo "hashes.txt not found."
                  # 创建 zip 包，只包含 overrides、manifest.json 和 modlist.html
                  zip -r ${{ env.ZIP_NAME }} overrides manifest.json modlist.html

            # 9. Read changelog for release body
            - name: Read changelog
              if: steps.setup.outputs.changelog_modified == 'true'
              id: read_changelog
              run: |
                  echo "changelog<<EOF" >> $GITHUB_OUTPUT
                  cat updater/versions/${{ env.VERSION }}/changelog.txt >> $GITHUB_OUTPUT
                  echo "EOF" >> $GITHUB_OUTPUT

            # 10. Create GitHub Release with changelog
            - name: Create GitHub Release
              if: steps.setup.outputs.changelog_modified == 'true'
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: "v${{ env.VERSION }}"
                  release_name: "Mel v${{ env.VERSION }}"
                  files: ${{ env.ZIP_NAME }}
                  body: "${{ steps.read_changelog.outputs.changelog }}"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
